language: node_js

node_js:
  - "lts/*"

before_script:
  - npm install -g gulp

addons:
  sonarcloud:
    organization: "dylan275"

script:
  - gulp
  - sonar-scanner -Dsonar.projectKey=dylan275_coreBuilder
